### ISSUE TITLE
support for sbt 1.4x

### ISSUE THREAD

**Issue by petahathub** [playframework/play-ebean#208] opened 2020-12-18 11:10 UTC
Hi,

I post an issue in payitech fork of play-ebean, but probably it would be good to let you know about it too:

https://github.com/payintech/play-ebean/issues/14

**Comment by Flo354** [comment] 2020-12-23 09:29
Hello there,

This is a duplicate of: https://github.com/playframework/play-ebean/issues/201
Which was fixed with this PR: https://github.com/playframework/play-ebean/pull/203

**Comment by felipebonezi** [comment] 2021-01-21 13:56
hey guys, how can I download the `6.1.0` version from maven?

**Comment by petahathub** [comment] 2021-01-21 15:40
> hey guys, how can I download the `6.1.0` version from maven?

I would try 
// https://mvnrepository.com/artifact/com.typesafe.play/play-ebean
libraryDependencies += "com.typesafe.play" %% "play-ebean" % "6.1.0-RC2"

**Comment by almothafar** [comment] 2021-02-17 10:00
@petahathub in sbt that does not work

**Comment by mkurz** [comment] 2021-03-24 15:57
@almothafar You need to add 
```
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.1.0-RC2")
```
to your `project/plugins.sbt`
Maybe you also need to add
```
resolvers += Resolver.bintrayRepo("playframework", "maven")
resolvers += Resolver.bintrayRepo("playframework", "sbt-plugin-releases")
```
but I think that isn't necessary, not sure however

**Comment by jmswenski** [comment] 2021-05-21 22:35
Made a PR to address the 1.4.x compatibility issues. 1.4.x introduced some breaking changes in the way that the incremental compiler tracks modifications to files and that figures into plugins that use those APIs to do further modifications on sources / binaries such as this one does with ebean enhancement. Hopefully we can get that merged in after we resolve the mess that Bintray made and get this project building into Sonatype.

**Comment by almothafar** [comment] 2021-06-01 12:21
To be honest I'm so hopeless now for this useless plugin and for sbt and play framework, the worst platform/framework that I dealt with in my whole career.

**Comment by Flo354** [comment] 2021-06-01 12:26
@almothafar you can't say that. 

It is true that Play! Framework is not really updated anymore. It is true that this plugin is now abandoned by the team. But Play! Framework does the job and does it good.

I am just wondering for the future if Play! Framework will follow Play Ebean and be abandonned.

**Comment by almothafar** [comment] 2021-06-01 12:45
@Flo354  for now yes, I agree with you, but Play framework recently is not so active as what it is used for, which is not the problem, I love Play framework itself, but if I can't use my libraries because of the mix of scala, sbt issues with other plugins and these breaking changes, I have 2 options, stay a few years behind or just abandoned Play framework ship for good.

I'm just really upset with how slow things are going on, yes I know it is based on contribution, I would love to contribute but I don't know scala, and my manager does not allow me to use my time to contribute to anything.

What made me take about this is the number of issues here like bintray is gone (and people fixed this issue even the sunset announced a long time ago), so I tried to use sonatype, even with this exist in sonatype but sbt can't resolve it, InteilliJ IDEA keep stuck because of this issue as sbt stuck somewhere of that error, so I have to restart IDE like 10 times last 30 minutes.

I tried `resolvers += Resolver.sonatypeRepo("snapshots")` and `addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.1.0-RC3")` or `addSbtPlugin("com.typesafe.play" % "play-ebean" % "6.1.0-RC3")` or  `addSbtPlugin("com.typesafe.play" % "play-ebean_2.13" % "6.1.0-RC3")` while it is here: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-ebean_2.13/

it just keeps failing and don't see it, errors like:

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.play:play-ebean_2.13;sbtVersion=1.0;scalaVersion=2.12:6.1.0-RC3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/play/play-ebean_2.13_2.12_1.0/6.1.0-RC3/play-ebean_2.13-6.1.0-RC3.pom
[error]   not found: C:\Users\AlMothafar\.ivy2\local\com.typesafe.play\play-ebean_2.13\scala_2.12\sbt_1.0\6.1.0-RC3\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/play-ebean_2.13/scala_2.12/sbt_1.0/6.1.0-RC3/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/play-ebean_2.13/scala_2.12/sbt_1.0/6.1.0-RC3/ivys/ivy.xml
```

also issues like #212 (before bintray go down, I converted my .properties file to .yaml and ebean accepted it so I wanted to give this a try but I ended up just wasting hours now)

Maybe I'm not correctly set configuration but there is no documentation either #211.

**Comment by lapidus79** [comment] 2021-07-11 17:17
> Made a PR to address the 1.4.x compatibility issues. 1.4.x introduced some breaking changes in the way that the incremental compiler tracks modifications to files and that figures into plugins that use those APIs to do further modifications on sources / binaries such as this one does with ebean enhancement. Hopefully we can get that merged in after we resolve the mess that Bintray made and get this project building into Sonatype.

I tried picking this code and seems to be working like a charm. Released it separately at https://github.com/lapidus79/play-ebean and published to maven with addSbtPlugin("io.github.lapidus79" % "sbt-play-ebean" % "6.2.2"). Try it out at own risk.

Hopefully the play-ebean publish flow can be fixed soon.

**Comment by leccyril** [comment] 2021-07-21 11:08
Hello, 

bintray was decommissionned... we are using play 2.8.2 and sbt-ebean 5.0.0 on which repo have to point ?

**Comment by almothafar** [comment] 2021-08-05 10:42
I see version 6.2.0 is there in sonatype:  https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-ebean_2.13/

But still can't import that:

```console
[warn] Unrecognized repository Scala Plugin Bundled Repository, ignoring it
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.


[warn]          com.typesafe.play:play-ebean:6.2.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run 'last update' for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.play:play-ebean;sbtVersion=1.0;scalaVersion=2.12:6.2.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/play/play-ebean_2.12_1.0/6.2.0/play-ebean-6.2.0.pom
[error]   not found: C:\Users\AlMothafar\.ivy2\local\com.typesafe.play\play-ebean\scala_2.12\sbt_1.0\6.2.0\ivys\ivy.xml
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-ebean_2.12_1.0/6.2.0/play-ebean-6.2.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/play-ebean/scala_2.12/sbt_1.0/6.2.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/play-ebean/scala_2.12/sbt_1.0/6.2.0/ivys/ivy.xml
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 11.0.5)
```

I got the following in my plugins.bt:

```
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.8")
addSbtPlugin("com.typesafe.play" % "play-ebean" % "6.2.0")
```

Just a note, why it is trying to get `play-ebean_2.12_1.0` while I got  `sbt.version=1.3.13` and `scalaVersion := "2.13.6"`, and why you don't publish to central mvn anymore? the last version is only 6.0.0 here: https://mvnrepository.com/artifact/com.typesafe.play/play-ebean

**Comment by JamesWilson3** [comment] 2021-08-20 04:24
Hi I am having the same problem and question as @almothafar with pointing to the latest / snapshot version of the eBean, and my IntelliJ also gets stuck trying to point it to Sonatype.

What is the official steps for pointing to the latest plugin properly? Is it possible to publish the plugin to maven as well? 

Thank you in advance.

**Comment by GithubUser8080** [comment] 2021-09-10 10:00
@JamesWilson3 @almothafar Hi, did happen to find any answer to these issues? Thanks

**Comment by almothafar** [comment] 2021-09-23 07:49
> @JamesWilson3 @almothafar Hi, did you happen to find any answer to these issues? Thanks

No, and no one responded and I don't think anybody will answer.

**Comment by leccyril** [comment] 2021-09-23 07:59
Hello, SBT and ebean etc have to be retrieve on new repository jfrog

**Comment by GithubUser8080** [comment] 2021-09-23 14:35
> Hello, SBT and ebean etc have to be retrieve on new repository jfrog

@leccyril Unfortunately only 6.0.0 exists there. 6.0.1 is still a release candidate, although in the README.md it is listed as a normal version

**Comment by almothafar** [comment] 2021-09-23 15:01
> > Hello, SBT and ebean etc have to be retrieve on new repository jfrog
> 
> @leccyril Unfortunately only 6.0.0 exists there. 6.0.1 is still a release candidate, although in the README.md it is listed as a normal version

Ther is also 6.2.0 in Sonatype https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-ebean_2.13/ but as I mentioned above, I was unable to get it

**Comment by GithubUser8080** [comment] 2021-09-23 15:07
I see, thanks. Looks like i have to use the com.payintech fork until this project is alive again. The ebean version in 6.0.0 is 2 years old

**Comment by Flo354** [comment] 2021-09-28 10:16
Repo from @lapidus79 works... But we can't rely on a single person for this.
Why isn't it available officially?

**Comment by lapidus79** [comment] 2021-09-28 10:38
To my understanding the ci/cd / publishing pipeline is broken and nobody knows how to fix this

**Comment by almothafar** [comment] 2021-09-28 11:40
> I see, thanks. Looks like i have to use the com.payintech fork until this project is alive again. The ebean version in 6.0.0 is 2 years old

You can update ebean without the need to wait for plugin to be updated, I got something like:

```scala
val oldPlayEbeanDependencies: Seq[sbt.ModuleID] =
  Seq(
    "javax.xml.bind" % "jaxb-api" % "2.3.1",
    "javax.activation" % "activation" % "1.1.1",
    "org.glassfish.jaxb" % "jaxb-runtime" % "2.3.5"
  )

val ebeanDependencies: Seq[sbt.ModuleID] =
  Seq(
    "io.ebean" % "ebean" % "12.12.0",
    "io.ebean" % "ebean-agent" % "12.12.0",
    "io.ebean" % "ebean-ddl-generator" % "12.12.0",
    "io.ebean" % "ebean-migration" % "12.12.1"
  )

libraryDependencies ++= Seq(
  guice,
  javaJdbc,
  javaWs,
  caffeine,
  filters,
  "com.typesafe.play" %% "play-json" % "2.9.2",
... etc
) ++ ebeanDependencies ++ oldPlayEbeanDependencies

```

**Comment by mkurz** [comment] 2021-12-21 09:01
Hi everyone, I am happy to chip in and fix play-ebean, however that won't happen in december. If you want to support me, please consider donating to our collective: https://www.playframework.com/sponsors

**Closed** 2022-01-25 08:30 UTC

**Comment by mkurz** [comment] 2022-01-28 22:25
play-ebean 6.2.0-RC4 released, please have a look at the release notes how to upgrade: https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC4. Please test and let us know if it works for you, thanks!
