### ISSUE TITLE
Integration with 11.x.x   

### ISSUE THREAD

**Issue by kpysniak** [playframework/play-ebean#141] opened 2017-12-05 10:09 UTC
Hey,

What are the plans on releasing play-ebean compatible with the latest ebean orm (11.x.x)? There are a number of great changes and improvements. Is there some timeline on that?

Thanks,
Karol

**Comment by PromanSEW** [comment] 2017-12-05 10:32
Dupe of #138

**Comment by marcospereira** [comment] 2017-12-18 13:28
Closed by #142.

**Closed by marcospereira** 2017-12-18 13:28 UTC

**Comment by marcospereira** [comment] 2017-12-18 13:29
By the way, see release 4.1.0.
